language: go

matrix:
  include:
    - os: linux
      go: 1.7
    - os: osx
      go: 1.7

before_deploy:
  - go get github.com/jteeuwen/go-bindata/...
  - make release
  - tar czf wego-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz wego

deploy:
  provider: releases
  api_key:
    secure: T+KL3sT9p6ZjT9CFUJdb0h91iDrJ7oCpxvL8arQoYis+horWyxwiIsD9HunJ19BjWD2G1Xs5GHAjQvIPLuYvj/vmDkfy26CB/ZSj0j2DnnTMeORw1tQ3mZxaDlL1GLziRHTU2Ugcbsp3cd/hWxlObki6Zv/hvQHl7KivA4Nptsc=
  file: wego-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

notifications:
  slack:
    secure: LkYa3LZFjPHgrBuLq8fzYog2/v5JwwJNekBjBjJjbBPmY/VP2oiykrZjM40yyrTxIstDXzaVZtqnhzn0SGXq0FFeV30h9OviLTjVhxwsZkXBl11ge/eCWSRPjKy33N8nVyDnHQBwNooW2ePR9UVDJ1c3mRAFo1PnU6sAAQtVJpI=
