language: go

go:
  - 1.7

install:
  - go get github.com/jteeuwen/go-bindata/...

before_deploy:
  - make release

deploy:
  provider: releases
  api_key:
    secure: DkfgP9l+PM9eSWSeeKbozCMkfCi6RdC5wvbVtI3UGlC2/XLZlotzWhE3b4kBWOnXZtkNn/pfBe6cHH3YlBFlMaRAUmfExE4bVElozvOuM2Cufv4HceSbJMGtJe2uoyTQjTRUAcP9ZsZUf6mFmXSjb0bcYuYkD7KXWU+M1ZXdhA0=
  file: hope_word
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
