language: go

go:
  - 1.7

before_deploy:
  - go get github.com/jteeuwen/go-bindata/...
  - make release

deploy:
  provider: releases
  api_key:
    secure: T+KL3sT9p6ZjT9CFUJdb0h91iDrJ7oCpxvL8arQoYis+horWyxwiIsD9HunJ19BjWD2G1Xs5GHAjQvIPLuYvj/vmDkfy26CB/ZSj0j2DnnTMeORw1tQ3mZxaDlL1GLziRHTU2Ugcbsp3cd/hWxlObki6Zv/hvQHl7KivA4Nptsc=
  file: wego
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
