language: go

go:
  - 1.7

before_deploy:
  - go build

deploy:
  provider: releases
  api_key:
    secure: fxuNoJK5j++2AaGMOmyzGBdpuSd9dFXzYyKgNJ3jsmonj0rN/otoK4Z1b7MbXpOEm8olYrFJrpLTNRaahGLgIezmB1UG92vTns2zh9hU3/8tqF4oCWiM1+jW7gECuxNNcY/BS0V9mu+/U0XPl3b5/Gpu50GmzGSToEAvZbapmHSVWdsqZLOw6UaD0oQlexpdWufQOSMxqvI0B9XVe1LV0LlICTqt8nJBRASNyb6m48hR8+mOxw0u4c0GLHJB/jGEN+5oDsDUohJOFTjhYoZvMhnjCAy1MO5NiYtt5gwszw2jOrm+YFrEscKrFxYcJrEvCEh1qB2FrDuPdnXfcl1bsFL8rr28FyLxEcMuWSPO8GnKu9b6Yv6ho0aMD228JrCAja/s7LhpgTvduN2k3AFH5Hw66C5hQuOU/FKZTme5dQOa6eTPvoCj+cla6gFYl1TjPvZFiN08OVPgYZoEqrzryfuEP8hQ1RJClFwsNQeO2tCTVRsZhj20oaL12e6Fg4WttIL0D3oYFWaAskfjTkjWvahAMtpRIpOHGK3n2Ma5HXUvBKvUTvLzJeENtAz+bgnTELZ+Tr4Q2DfKEKMGOggkSJBRti2gRDcUmQwyFmRP98B0AfIwrlx0PnEMtDwTpdkEMSLVmimlrpTB738bpPO5rf/yeqRieeXFSp/Wyt0EJIg=
  file: hope_server
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
